name: flutter_stripe_demo
description: Demo project showing Stripe Checkout integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  webview_flutter: ^1.0.0
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
